### ISSUE TITLE
ﬄ glyph missing in Italics

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Exo-1.0#8]
Please merge #7  first then add this glyph to the Italics.

**Comment by pichotta** [comment]
/ffl  is visualized in italic sources  ?

![:ffl Exo Thins](https://user-images.githubusercontent.com/6576107/77124701-fd9ef080-6a19-11ea-96c0-3c5f6d454421.png)
![:ffl Exo Blacks](https://user-images.githubusercontent.com/6576107/77124703-0099e100-6a1a-11ea-9c9e-5bac31f7cf19.png)

**Comment by pichotta** [comment]
still investigating  
perhaps it was the /germandbls.smcp?

**Comment by pichotta** [comment]
glyphs missing in diff reports ffl lig missing 'after'
but glyphs modified shows the ffl lig present 'before' and 'after'

![diff modified before](https://user-images.githubusercontent.com/6576107/77129542-c38a1a80-6a2a-11ea-8e0b-a3dcdcb9d27c.png)

![diff modified after](https://user-images.githubusercontent.com/6576107/77129544-c5ec7480-6a2a-11ea-8f16-233715a29d72.png)

**Comment by pichotta** [comment]
deleted duplicate /ffl lig under different glyph name
deleted duplicate /germandbls under diff name
hard encoded f_f, f_i, f_f_i, f_f_l, f_t ligs with U+ values

**Comment by m4rc1e** [comment]
Thanks Jill!
