### ISSUE TITLE
OS/2 usWeightClass

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Exo-1.0#9]
@m4rc1e
The two designspace files for this family look to have the same values. 
In the romans the FB issues a warning about the Thin. In the Italics FB issues a fail instead of a warning.

![Exo Roman Warning ](https://user-images.githubusercontent.com/6576107/77253534-509ec080-6c31-11ea-9fcd-c02c3f956cdd.png)

![Exo Roman Fail ](https://user-images.githubusercontent.com/6576107/77253536-5399b100-6c31-11ea-93eb-0f039b15ce0d.png)

**Comment by m4rc1e** [comment]
The fonts are correct, this is an issue with Fontbakery. Please ignore
